# Label for GitHub UI
name: Run Python Tests

# Defines the 'triggers'
on: [push, pull_request]

# The start of the work, a workflow can have multiple
jobs:
    test:  # Custom ID for this job
        runs-on: ubuntu-latest  # Defines the environment for the job

        # The individual taks that happen in order
        steps:
            - name: Check out code  # Describes this specific step
              # 'uses' a pre-made action from the marketplace
              uses: actions/checkout@v4  # Copy the repo files onto the VM

            - name: Set up Python
              uses: actions/setup-python@v5
              with:  # 'with' is used to pass extra info to a 'uses' action
                    python-version: '3.10'

            - name: Install dependencies
              run: |  # Run is used to execute commands in the terminal, '|' allows for multiple lines
                python -m pip install --upgrade pip  
                pip install -r requirements.txt  
            
            - name: Run lint
              # Black tidies up the code, flake8 checks for style and errors
              run: |
                pip install flake8 black
                black . --check
                flake8 . --count --max-line-length=88 --extend-ignore=E203,E302 --statistics

            - name: Run tests
              # A single command, therefore no '|'
              run: python -m pytest tests/test_predict.py

            - name: Build Docker image
              run: |
                docker build -t my-app:latest .

            - name: Log in to Docker Hub
              # echo is a shell script like f"
              # ( | ) Tells the terminal to take the output of the echo command
              # stdin passes from the outside to the inside
                                                          # ( -u )Login as user
              run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

            - name: Tag image
              run: |  # Rename to docker_username/my-app:latest
                docker tag my-app:latest ${{ secrets.DOCKER_USERNAME }}/my-app:latest

            - name: Push image
              run: |
                docker push ${{ secrets.DOCKER_USERNAME }}/my-app:latest
